### ISSUE TITLE
soil-moisture-monitor yaml does not compile in ESPHome 2025.08.0

### ISSUE THREAD

**Issue by jsbrich** [Seeed-Studio/xiao-esphome-projects#17]
I get the following compilation error when trying to compile the yaml at [https://github.com/Seeed-Studio/xiao-esphome-projects/blob/main/projects/xiao-soil-moisture-monitor/xiao-soil-moisture-monitor.yaml](url)

`Compiling .pioenvs/xiao-soil-2/src/esphome/components/esp32/core.cpp.o
src/esphome/components/deep_sleep/deep_sleep_esp32.cpp: In member function 'void esphome::deep_sleep::DeepSleepComponent::deep_sleep_()':
src/esphome/components/deep_sleep/deep_sleep_esp32.cpp:116:49: error: enum constant in boolean context [-Werror=int-in-bool-context]
  116 |     if (this->wakeup_pin_->get_flags() && gpio::FLAG_PULLUP) {
      |                                                 ^~~~~~~~~~~
src/esphome/components/deep_sleep/deep_sleep_esp32.cpp:118:56: error: enum constant in boolean context [-Werror=int-in-bool-context]
  118 |     } else if (this->wakeup_pin_->get_flags() && gpio::FLAG_PULLDOWN) {
      |                                                        ^~~~~~~~~~~~~
src/esphome/components/deep_sleep/deep_sleep_esp32.cpp:123:5: error: 'gpio_deep_sleep_hold_en' was not declared in this scope; did you mean 'gpio_sleep_sel_en'?
  123 |     gpio_deep_sleep_hold_en();
      |     ^~~~~~~~~~~~~~~~~~~~~~~
      |     gpio_sleep_sel_en
cc1plus: some warnings being treated as errors
*** [.pioenvs/xiao-soil-2/src/esphome/components/deep_sleep/deep_sleep_esp32.cpp.o] Error 1`

**Comment by StarSphere-1024** [comment]
Hi @jsbrich,
Thank you for reporting this issue. The compilation error is caused by a known bug in ESPHome 2025.8.0 for the ESP32-C6, related to the deep_sleep component (tracked in [esphome/esphome#10234](https://github.com/esphome/esphome/issues/10234)). It stems from improper handling of GPIO pull-up/down flags and an undefined gpio_deep_sleep_hold_en function for ESP32-C6 in ESP-IDF.
Workaround: Downgrade to ESPHome 2025.7.0, which compiles successfully for this configuration. You can do this via:

CLI: pip install esphome==2025.7.0, then esphome compile xiao-soil-moisture-monitor.yaml.
Home Assistant add-on: Uninstall the current add-on and install version 2025.7.0.

Additionally, remove the explicit framework.version: "5.2.1" from the YAML to use the recommended ESP-IDF version and avoid related warnings.
We're monitoring the upstream issue for a fix in a future ESPHome release. Please try the workaround and let us know if you encounter further issues.

**Comment by JoseIvey** [comment]
The cose below address the complie issues and gets rid of references to custom includes and old versions while retaining the original functionality. It does require a secrets.yaml.

`substitutions:
  name: "xiao-plant-monitor"
  friendly_name: Xiao Plant Monitor
  upper_devicename: Xiao Plant Moisture Monitor
  board_name: esp32-c6-devkitc-1
  board_variant_name: ESP32C6
  sensor_update_interval: 300s
  sleep_duration_dry: 900000
  sleep_duration_almost_dry: 3600000
  sleep_duration_normal: 28800000
  max_battery_voltage: 1.5

# special packaged configs
# packages:

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  min_version: 2025.5.0
  on_boot: 
    then:
      # - output.turn_off: gpio_3_output
      - output.turn_on: gpio_14_output
      - light.turn_on:
          id: pwm_led
          brightness: 68%  # Set 68% duty cycle
      - delay: 1s
      - script.execute: check_moisture_once
  

esp32:
  board: ${board_name}
  variant: ${board_variant_name}
  flash_size: 4MB 
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
 
# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
    #ssid: ${friendly_name}
    #password: !secret fallback_password

# Captive Config portal
# captive_portal:

# LED Yellow D10 18
# LED RED D9  20
# LED Green D8 19
# button D2  2

# Battery D0 0
# PWM out D3 21
# Soil sensor D1  1

output:
  - platform: gpio
    pin: GPIO18
    id: yellow_led_output

  - platform: gpio
    pin: GPIO19
    id: green_led_output

  - platform: gpio
    pin: GPIO20
    id: red_led_output

  - platform: ledc
    pin: GPIO21  
    id: pwm_output
    frequency: 200kHz  # Set the frequency to 200kHz

  - platform: gpio
    pin: GPIO14
    id: gpio_14_output

light:
  - platform: binary
    id: yellow_led
    output: yellow_led_output

  - platform: binary
    id: green_led
    output: green_led_output

  - platform: binary
    id: red_led
    output: red_led_output

  - platform: monochromatic
    output: pwm_output
    id: pwm_led
    name: "200kHz PWM"
    internal: true
    default_transition_length: 0s

script:
  - id: red_led_blink
    mode: restart
    then:
      - repeat:
          count: 10
          then:
            - light.turn_on: red_led
            - delay: 500ms
            - light.turn_off: red_led
            - delay: 500ms

  - id: green_led_blink
    mode: restart
    then:
      - repeat:
          count: 10
          then:
            - light.turn_on: green_led
            - delay: 500ms
            - light.turn_off: green_led
            - delay: 500ms

  - id: fast_blink_green
    then:
      - repeat:
          count: 5
          then:
            - light.turn_on: green_led
            - delay: 200ms
            - light.turn_off: green_led
            - delay: 200ms

  - id: fast_blink_red
    then:
      - repeat:
          count: 5
          then:
            - light.turn_on: red_led
            - delay: 200ms
            - light.turn_off: red_led
            - delay: 200ms

  - id: red_led_blink_3_times
    then:
      - repeat:
          count: 1
          then:
            - light.turn_on: red_led
            - delay: 1000ms
            - light.turn_off: red_led
            - delay: 100ms
            
  - id: yellow_led_blink_3_times
    then:
      - repeat:
          count: 1
          then:
            - light.turn_on: yellow_led
            - delay: 1000ms
            - light.turn_off: yellow_led
            - delay: 100ms

  - id: green_led_blink_3_times
    then:
      - repeat:
          count: 1
          then:
            - light.turn_on: green_led
            - delay: 1000ms
            - light.turn_off: green_led
            - delay: 100ms

  - id: do_calibration
    then:
      - deep_sleep.prevent: deep_sleep_control
      - logger.log: "Starting calibration"
      - script.execute: red_led_blink
      - delay: 10s
      - script.stop: red_led_blink
      - lambda: |-
          float sum = 0;
          for (int i = 0; i < 10; i++) {
            id(soil_sensor).update();
            sum += id(soil_sensor).state;
            delay(200);
          }
          id(dry_value) = sum / 10.0;
          ESP_LOGI("calibration", "Dry value: %f", id(dry_value));

      - delay: 3s

      - script.execute: green_led_blink
      - delay: 10s
      - script.stop: green_led_blink
      - lambda: |-
          float sum = 0;
          for (int i = 0; i < 10; i++) {
            id(soil_sensor).update();
            sum += id(soil_sensor).state;
            delay(200);
          }
          id(wet_value) = sum / 10.0;
          ESP_LOGI("calibration", "Wet value: %f", id(wet_value));

      - delay: 3s

      - lambda: |-
          if (id(dry_value) > id(wet_value)) {
            ESP_LOGI("calibration", "Calibration success");
            id(fast_blink_green).execute();
          } else {
            ESP_LOGW("calibration", "Calibration failed");
            id(fast_blink_red).execute();
          }

      - delay: 3s
      - script.execute: check_moisture_once
      - delay: 3s
      - deep_sleep.enter: deep_sleep_control

  - id: check_moisture_once
    then:
      - lambda: |-
          for(int i = 0; i < 10; i++){
            id(soil_sensor).update();
            delay(200);
          }
          float moisture = id(soil_sensor).state;
          ESP_LOGI("moisture_check", "Moisture reading: %f", moisture);
          float Diff = id(dry_value) - id(wet_value);
          ESP_LOGI("moisture_check", "Diff is: %f", Diff);
          ESP_LOGI("moisture_check", "ref_dry Diff is: %f",id(dry_value) - Diff * id(ref_dry));
          ESP_LOGI("moisture_check", "ref_wet Diff is: %f",id(dry_value) - Diff * id(ref_wet));
          if (moisture >= (id(dry_value) - Diff * id(ref_dry))) {  // The drier -> the higher the voltage
            id(red_led_blink_3_times).execute();
            id(deep_sleep_control).set_sleep_duration(${sleep_duration_dry});
          } else if(moisture >  (id(dry_value) - Diff * id(ref_wet)) && moisture < (id(dry_value) - Diff * id(ref_dry))){
            id(yellow_led_blink_3_times).execute();
            id(deep_sleep_control).set_sleep_duration(${sleep_duration_almost_dry});
          }else{
            // moisture >  (id(dry_value) - Diff * id(ref_wet))
            id(green_led_blink_3_times).execute();
            id(deep_sleep_control).set_sleep_duration(${sleep_duration_normal});
          }

globals:
  - id: button_press_count
    type: int
    restore_value: no
    initial_value: '0'
    
  - id: dry_value
    type: float
    restore_value: yes
    initial_value: '2.75'
    
  - id: wet_value
    type: float
    restore_value: yes
    initial_value: '1.2'
    
  - id: ref_dry
    type: float
    restore_value: no
    initial_value: "0.23"
    
  - id: ref_wet
    type: float
    restore_value: no
    initial_value: "0.58"

deep_sleep:
  id: deep_sleep_control
  run_duration: 120s  
  sleep_duration: 180min  
  wakeup_pin: 
    number: GPIO2 
    inverted: true
    allow_other_uses: true
    mode: INPUT_PULLUP


#external_components:
  #- source: github://pr#7942
  #  components: [ "adc" ]

 # - source:
    #  type: git
    #  url: https://github.com/ackPeng/esphome.git
    #  ref: api
    #components: [ api ]
    #refresh: 0s



binary_sensor:
  - platform: status
    name: "Status"
    
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      allow_other_uses: true
    id: my_button
    on_press:
      - lambda: |-
          id(button_press_count)++;
      - delay: 1s  # Delay 1 second to see if the button is pressed 3 times in a row
      - lambda: |-
          if (id(button_press_count) == 3) {
            id(button_press_count) = 0;
            id(do_calibration).execute();  // Trigger calibration process
          } else if (id(button_press_count) == 1) {
            id(button_press_count) = 0;
            id(check_moisture_once).execute();  // Perform an ADC decision
          } else {
            id(button_press_count) = 0;
          }
          
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: ${sensor_update_interval}

  - platform: uptime
    type: seconds
    name: "Uptime Sensor"
    unit_of_measurement: "m"
    accuracy_decimals: 3
    update_interval: ${sensor_update_interval}
    filters:
      - multiply: 0.01666666666667
      
  - platform: adc
    id: soil_sensor
    pin: GPIO1
    name: "Soil moisture measurement"
    update_interval: ${sensor_update_interval}
    internal: true
    attenuation: 12db

  - platform: adc
    pin: GPIO0
    name: "Battery Percent"
    attenuation: 12db
    filters:                     # When the battery drops below 1V, it is dead.
      - lambda: |-
          if (x < 1.0) {
            return 0.0;
          } else {
            return ((x - 1.0) / (${max_battery_voltage} - 1.0)) * 100.0;
          } 
    unit_of_measurement: "%"
    update_interval: ${sensor_update_interval}
    force_update: True

text_sensor:
  - platform: template
    name: "Soil Moisture Status"
    id: soil_status
    lambda: |-
      float value = id(soil_sensor).state;
      float Diff = id(dry_value) - id(wet_value);
      if (value >= (id(dry_value) - Diff * id(ref_dry))) {
        return {"Dry"};
      } else if (value > (id(dry_value) - Diff * id(ref_wet)) && value < (id(dry_value) - Diff * id(ref_dry))) {
        return {"Almost Dry"};
      } else {
        return {"Normal Moisture"};
      }
    update_interval: never  # 不让自动触发上报，我们自己控制 Don't let the automatic trigger report, we control it ourselves


interval:
  - interval: 5s
    then:
      - text_sensor.template.publish:
          id: soil_status
          state: !lambda |-
            return "";
      - delay: 10ms
      - text_sensor.template.publish:
          id: soil_status
          state: !lambda |-
            float value = id(soil_sensor).state;
            float Diff = id(dry_value) - id(wet_value);
            if (value >= (id(dry_value) - Diff * id(ref_dry))) {
              id(deep_sleep_control).set_sleep_duration(${sleep_duration_dry});
              return "Dry";
            } else if (value > (id(dry_value) - Diff * id(ref_wet)) && value < (id(dry_value) - Diff * id(ref_dry))) {
              id(deep_sleep_control).set_sleep_duration(${sleep_duration_almost_dry});
              return "Almost Dry";
            } else {
              id(deep_sleep_control).set_sleep_duration(${sleep_duration_dry});
              return "Normal Moisture";
            }  
`
